const products = [
  {
    id: 1,
    name: "Organic Tomatoes",
    type: "Vegetable",
    image: "/public/images/product/tomato.png",
    price: 5.99,
    discount: 10,
    stars: "⭐️⭐️⭐️⭐️⭐️",
  },
  {
    id: 2,
    name: "Organic Orange",
    type: "Fruit",
    image: "/public/images/product/orange.png",
    price: 3.49,
    discount: 5,
    stars: "⭐️⭐️⭐️⭐️",
  },
  {
    id: 3,
    name: "Organic Strawberry",
    type: "Fruit",
    image: "/public/images/product/strawberry.png",
    price: 4.99,
    discount: 15,
    stars: "⭐️⭐️⭐️⭐️⭐️",
  },
  {
    id: 4,
    name: "Organic Orange",
    type: "Fruit",
    image: "/public/images/product/orange2.png",
    price: 8.99,
    discount: 20,
    stars: "⭐️⭐️⭐️⭐️",
  },
  {
    id: 5,
    name: "Organic Corn",
    type: "Vegetable",
    image: "/public/images/product/corn.png",
    price: 60.00,
    discount: 10,
    stars: "⭐️⭐️⭐️⭐️⭐️",
  },
  {
    id: 6,
    name: "Organic Apple",
    type: "Fruit",
    image: "/public/images/product/apple.png",
    price: 3.99,
    discount: 5,
    stars: "⭐️⭐️⭐️⭐️",
  },
  {
    id: 7,
    name: "Organic Cabbage",
    type: "Vegetable",
    image: "/public/images/product/cabbage.png",
    price: 3.99,
    discount: 5,
    stars: "⭐️⭐️⭐️⭐️",
  },
  {
    id: 8,
    name: "Oraganic Mango",
    type: "Fruit",
    image: "/public/images/product/mango.png",
    price: 3.99,
    discount: 5,
    stars: "⭐️⭐️⭐️⭐️",
  },
];

export default products
